### ISSUE TITLE
date: format_date and earliest_date could take **kwargs

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-utils#12]
Just like `normalize_date` does: https://github.com/inspirehep/inspire-utils/blob/a3d30224979f0a6ca78b48edb6cdfdb29c18ea0b/inspire_utils/date.py#L196

**Comment by michamos** [comment]
They are supposed to act on a schema-compliant date, so they are reading the string with the simpler (and stricter) `loads` instead of `parse`. That method doesn't take `**kwargs`.

**Comment by jacquerie** [comment]
Whoops, didn't notice that. Makes sense.
