### ISSUE TITLE
name: capitalization, should we use the ``force`` (parameter)?

### ISSUE THREAD

**Issue by chris-asl** [inspirehep/inspire-utils#34]
`HumanName` supports capitalization of names ([related docs](http://nameparser.readthedocs.io/en/latest/usage.html#capitalization-support)).  

Currently, we have capitalization enabled, which does a best effort to capitalize names.  
Although, without the `force=True` it doesn't do anything on mixed case names.  

In addition to the example from their docs, the same happens for names like: `Ellis, john`, the result will be the same, and not `Ellis, John`.  
For the aforementioned case it seems logical to use it, but for the case of their example `Shirley Maclaine` (converting it to `Shirley MacLaine`) I don't know.

@michamos @jacquerie 
It's not something that I need for authors search, but something to keep in mind and decide upon.

**Comment by jacquerie** [comment]
If you really, really, really want to split hairs about this, https://en.wikipedia.org/wiki/Bell_hooks uses only lowercase letters in her name, so even `capitalize` might be wrong. But let's say that it's good enough for us...
